#!/usr/bin/env bash
# install.sh — install a 'skillctl' launcher into ~/.local/bin so it can be
# invoked from anywhere without typing 'python3 scripts/skillctl.py'.
#
# Behavior:
#   - Creates ~/.local/bin/skillctl as a tiny launcher that exec's
#     python3 against this repo's scripts/skillctl.py (absolute path).
#   - Refuses to overwrite a different existing file unless --force.
#   - Idempotent: re-running with the same repo path is a no-op.
#   - Warns if ~/.local/bin is not on PATH.
#
# Uninstall: rm ~/.local/bin/skillctl
#
# Usage:
#   bash scripts/install.sh           # install
#   bash scripts/install.sh --force   # overwrite an unrelated existing file
#   bash scripts/install.sh --dry-run # print what would happen, don't write
#   bash scripts/install.sh --bin-dir <dir>  # alternate target dir

set -euo pipefail

# --- defaults ---
BIN_DIR="${HOME}/.local/bin"
FORCE=0
DRY_RUN=0

# --- args ---
while [ $# -gt 0 ]; do
  case "$1" in
    --force)    FORCE=1 ;;
    --dry-run)  DRY_RUN=1 ;;
    --bin-dir)  shift; BIN_DIR="$1" ;;
    -h|--help)
      sed -n '2,18p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *)
      echo "unknown option: $1" >&2
      exit 2
      ;;
  esac
  shift
done

# --- color helpers (TTY only) ---
if [ -t 1 ] && command -v tput >/dev/null 2>&1; then
  BOLD="$(tput bold)"; DIM="$(tput dim)"
  GREEN="$(tput setaf 2)"; YELLOW="$(tput setaf 3)"; RESET="$(tput sgr0)"
else
  BOLD=""; DIM=""; GREEN=""; YELLOW=""; RESET=""
fi

ok()   { echo "${GREEN}✓${RESET} $*"; }
warn() { echo "${YELLOW}!${RESET} $*"; }
info() { echo "${BOLD}==>${RESET} $*"; }
hint() { echo "   ${DIM}$*${RESET}"; }

# --- locate the skillctl source script ---
SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" && pwd )"
SKILLCTL_PY="${SCRIPT_DIR}/skillctl.py"

if [ ! -f "$SKILLCTL_PY" ]; then
  echo "ERROR: skillctl.py not found at $SKILLCTL_PY" >&2
  exit 1
fi

LAUNCHER="${BIN_DIR}/skillctl"

# --- pre-flight: existing file check ---
if [ -e "$LAUNCHER" ] || [ -L "$LAUNCHER" ]; then
  # If it is already pointing at our skillctl.py, treat as already-installed.
  existing_target=""
  if [ -f "$LAUNCHER" ]; then
    existing_target="$(grep -oE '/[^"]+/skillctl\.py' "$LAUNCHER" 2>/dev/null | head -1 || true)"
  fi
  if [ "$existing_target" = "$SKILLCTL_PY" ]; then
    ok "${LAUNCHER} already points at this repo — nothing to do"
  elif [ "$FORCE" -ne 1 ]; then
    warn "${LAUNCHER} already exists and points elsewhere (or is unrelated)"
    hint "Inspect:  cat ${LAUNCHER}"
    hint "Replace:  bash scripts/install.sh --force"
    hint "Or remove first:  rm ${LAUNCHER}"
    exit 1
  fi
fi

# --- write the launcher ---
info "installing skillctl launcher → ${LAUNCHER}"
hint  "wraps  python3 ${SKILLCTL_PY}"

LAUNCHER_BODY="#!/usr/bin/env bash
# auto-generated by sincerity-skills/scripts/install.sh — do not edit
# regenerate with: bash $(printf '%q' "$SCRIPT_DIR")/install.sh --force
exec python3 \"${SKILLCTL_PY}\" \"\$@\"
"

if [ "$DRY_RUN" -eq 1 ]; then
  info "[dry-run] would mkdir -p ${BIN_DIR}"
  info "[dry-run] would write ${LAUNCHER}:"
  printf '%s' "$LAUNCHER_BODY" | sed 's/^/    /'
  info "[dry-run] would chmod +x ${LAUNCHER}"
else
  mkdir -p "$BIN_DIR"
  printf '%s' "$LAUNCHER_BODY" > "$LAUNCHER"
  chmod +x "$LAUNCHER"
  ok "installed"
fi

# --- PATH check ---
case ":${PATH}:" in
  *":${BIN_DIR}:"*)
    ok "${BIN_DIR} is on PATH"
    ;;
  *)
    warn "${BIN_DIR} is NOT on PATH"
    case "${SHELL:-}" in
      */zsh)  rcfile="~/.zshrc" ;;
      */bash) rcfile="~/.bashrc" ;;
      *)      rcfile="your shell rc file" ;;
    esac
    hint "Add to ${rcfile}:"
    hint "  export PATH=\"${BIN_DIR}:\$PATH\""
    hint "Then open a new terminal (or:  source ${rcfile})."
    ;;
esac

if [ "$DRY_RUN" -eq 0 ]; then
  echo
  info "try it:"
  hint "  skillctl targets"
  hint "  skillctl status"
fi
